[package]
name = "iox_data_generator"
default-run = "iox_data_generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1.6"
chrono = { version = "0.4", default-features = false }
clap = { version = "4", features = ["derive", "env", "cargo"] }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
handlebars = "5.1"
humantime = "2.1.0"
influxdb2_client = { path = "../influxdb2_client" }
itertools = "0.13.0"
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch = { path = "../mutable_batch" }
parquet_file = { path = "../parquet_file" }
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.10"
schema = { path = "../schema" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
snafu = "0.8"
tokio = { version = "1.38", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
toml = "0.8.14"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", default-features = false }

[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["rayon"]}
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "point_generation"
harness = false

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
