[package]
name = "sharder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
data_types = { path = "../data_types" }
mutable_batch = { path = "../mutable_batch" }
parking_lot = "0.12"
siphasher = "1.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["async_tokio", "rayon"]}
hashbrown = { workspace = true }
mutable_batch_lp = { path = "../mutable_batch_lp" }
rand = "0.8.5"

[[bench]]
name = "sharder"
harness = false

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
