[package]
name = "versioned_file_store"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.81"
bytes = "1.6.0"
futures = "0.3.30"
object_store = { workspace = true }
tokio = "1.38.0"
uuid = "1.10.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.10.1"
