[package]
name = "iox_query_influxql"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arrow = { workspace = true }
chrono-tz = { version = "0.9" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
generated_types = { path = "../generated_types" }
influxdb_influxql_parser = { path = "../influxdb_influxql_parser" }
iox_query = { path = "../iox_query" }
iox_query_params = { path = "../iox_query_params" }
itertools = "0.13.0"
observability_deps = { path = "../observability_deps" }
predicate = { path = "../predicate" }
query_functions = { path = "../query_functions" }
regex = "1"
schema = { path = "../schema" }
serde_json = "1.0.128"
thiserror = "1.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
assert_matches = "1"
chrono = { version = "0.4", default-features = false }
insta = { version = "1", features = ["yaml"] }
test_helpers = { path = "../test_helpers" }
