[package]
name = "mutable_batch_tests"
description = "MutableBatch integration tests and benchmarks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
flate2 = "1.0"

[dev-dependencies]
bytes = "1.9"
criterion = { version = "0.5", default-features = false, features = ["rayon"] }
data_types = { path = "../data_types", default-features = false }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
prost = { workspace = true }

[[bench]]
name = "statistics"
harness = false

[[bench]]
name = "write_lp"
harness = false

[[bench]]
name = "write_pb"
harness = false

[lib]
# Allow --save-baseline to work
# https://github.com/bheisler/criterion.rs/issues/275
bench = false
