[package]
name = "object_store_metrics"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1.80"
bytes = "1.6"
futures = "0.3"
iox_time = { version = "0.1.0", path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
object_store = { workspace = true }
pin-project = "1.1.5"
tokio = { version = "1.37", features = ["io-util"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
snafu = "0.8"
tokio = { version = "1.37", features = ["macros", "io-util"] }
